Enum classes and Listing Types
Axieum/IAB207.Assignment_03 pull request #13
Opened 2020-10-03 14:06 UTC by jordauld1

Adding more database inputs for listing using Enums

Fixes#

2020-10-03 14:08 UTC, Axieum submitted a review, later dismissed
![](https://media.giphy.com/media/YKdm91XONLTaw/source.gif)

2020-10-03 14:45 UTC, Axieum submitted a review, later dismissed

2020-10-04 12:41 UTC, Axieum requested changes

2020-10-04 12:41 UTC, Axieum commented on auction/forms.py
> +    condition = FileField('Condition', validators=[InputRequired()])
Should these all be file upload fields? 😂

2020-10-04 12:41 UTC, Axieum commented on auction/models.py
> +    8K = '7680x4320'
I think this is illegal, correct me if I'm wrong?

2020-10-04 16:32 UTC, jordauld1 commented on auction/forms.py
> +    condition = FileField('Condition', validators=[InputRequired()])
Yikes, that's embarrassing, must've been tired last night 😂.

Would I make the enum ones SelectFields or just have them as StringFields? We'd probably want SelectFields if we were actually going to use the wtform generated one but since we're not, I'm not sure if it will matter or not?

This is what I've got now.
![image](https://user-images.githubusercontent.com/50126039/95020903-3bf7b680-06b1-11eb-8121-78407ec82dbb.png)

2020-10-05 00:08 UTC, Axieum commented on auction/forms.py
> +    condition = FileField('Condition', validators=[InputRequired()])
I think you're spot on with using Select fields. We can still dynamically put the select options in the form.

2020-10-05 01:03 UTC, isaacwoodrow approved these changes

2020-10-05 02:30 UTC, Axieum submitted a review, later dismissed

2020-10-05 07:01 UTC, Axieum approved these changes

2020-10-05 16:02 UTC, Axieum approved these changes

2020-10-05 16:02 UTC, merged